In [3]:
import pandas as pd
import numpy as np

In [3]:
# Exemplo de dados
data = {
    'Fornecedor': ['A', 'B', 'C', 'D'],
    'C1': [4, 3, 5, 2],
    'C2': [3, 4, 2, 5],
    'C3': [5, 2, 4, 3],
    'C4': [2, 5, 3, 4]
}
df = pd.DataFrame(data)

In [3]:
df.head()

Fornecedor  C1  C2  C3  C4
0          A   4   3   5   2
1          B   3   4   2   5
2          C   5   2   4   3
3          D   2   5   3   4

In [5]:
# Definindo os pesos
pesos = np.array([0.3, 0.2, 0.2, 0.3])

In [6]:
# Função de preferência usual
def preference_function(d, p=0):
    return 1 if d > p else 0

In [3]:
print(preference_function)


<function preference_function at 0x10c6451c0>


In [8]:
# Matriz de preferência
def preference_matrix(df, pesos):
    n = df.shape[0]
    m = df.shape[1] - 1
    P = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            if i != j:
                P[i, j] = sum(pesos[k] * preference_function(df.iloc[i, k+1] - df.iloc[j, k+1]) for k in range(m))

    return P

P = preference_matrix(df, pesos)


[[0.  0.5 0.4 0.5]
 [0.5 0.  0.5 0.6]
 [0.6 0.5 0.  0.5]
 [0.5 0.4 0.5 0. ]]


In [10]:
#Fluxos de saída e entrada
fluxo_saida = P.sum(axis=1)
fluxo_entrada = P.sum(axis=0)


In [11]:
# Fluxo líquido
fluxo_liquido = fluxo_saida - fluxo_entrada


In [12]:
# Adicionando ao DataFrame
df['Fluxo Líquido'] = fluxo_liquido

In [13]:
# Ordenando fornecedores
df = df.sort_values(by='Fluxo Líquido', ascending=False)

In [14]:
print(df)

  Fornecedor  C1  C2  C3  C4  Fluxo Líquido
1          B   3   4   2   5            0.2
2          C   5   2   4   3            0.2
0          A   4   3   5   2           -0.2
3          D   2   5   3   4           -0.2
